// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [
      { type: "text", text: "N\xE3o autenticado. Conecte-se novamente." }
    ],
    isError: true
  };
}
function failure(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-events.ts
var list_events_default = defineTool({
  name: "list_events",
  title: "Listar eventos",
  description: "Lista os eventos vis\xEDveis para o usu\xE1rio conectado, com data, status, local e limite de inscri\xE7\xF5es.",
  inputSchema: {
    status: z.enum(["draft", "published", "closed"]).optional().describe("Filtra por status do evento."),
    search: z.string().optional().describe("Busca por parte do nome do evento."),
    limit: z.number().int().optional().describe("M\xE1ximo de eventos (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("events").select(
      "id, name, slug, status, event_date, event_end_date, location_type, location_value, registration_limit, capacity, registration_deadline, created_at"
    ).order("event_date", { ascending: false }).limit(max);
    if (status) query = query.eq("status", status);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return ok({ count: data?.length ?? 0, events: data ?? [] });
  }
});

// src/lib/mcp/tools/get-event-stats.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_event_stats_default = defineTool2({
  name: "get_event_stats",
  title: "Estat\xEDsticas do evento",
  description: "Retorna o resumo de um evento: total de inscri\xE7\xF5es, presentes (check-in), pendentes e cancelados.",
  inputSchema: {
    event_id: z2.string().describe("ID (uuid) do evento.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: event, error: eventError } = await supabase.from("events").select("id, name, slug, status, event_date, event_end_date, capacity, registration_limit").eq("id", event_id).maybeSingle();
    if (eventError) return failure(eventError.message);
    if (!event) return failure("Evento n\xE3o encontrado ou sem permiss\xE3o de acesso.");
    const { data: rows, error } = await supabase.from("registrations").select("status, checked_in_at").eq("event_id", event_id);
    if (error) return failure(error.message);
    const registrations = rows ?? [];
    const byStatus = {};
    for (const row of registrations) {
      const key = String(row.status ?? "unknown");
      byStatus[key] = (byStatus[key] ?? 0) + 1;
    }
    const checkedIn = registrations.filter((r) => r.checked_in_at).length;
    const active = registrations.filter((r) => String(r.status) !== "cancelled").length;
    return ok({
      event,
      total_registrations: registrations.length,
      active_registrations: active,
      checked_in: checkedIn,
      attendance_rate_percent: active ? Math.round(checkedIn / active * 1e3) / 10 : 0,
      by_status: byStatus
    });
  }
});

// src/lib/mcp/tools/list-registrations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_registrations_default = defineTool3({
  name: "list_registrations",
  title: "Listar inscritos",
  description: "Lista os inscritos de um evento com nome, e-mail, WhatsApp, status e hor\xE1rio de check-in. Permite buscar por nome/e-mail/telefone.",
  inputSchema: {
    event_id: z3.string().describe("ID (uuid) do evento."),
    search: z3.string().optional().describe("Busca por nome, e-mail ou WhatsApp."),
    status: z3.string().optional().describe("Filtra pelo status da inscri\xE7\xE3o (ex.: pending, attended, cancelled)."),
    checked_in: z3.boolean().optional().describe("true = apenas quem fez check-in; false = apenas quem ainda n\xE3o fez."),
    limit: z3.number().int().optional().describe("M\xE1ximo de inscritos (padr\xE3o 50, m\xE1ximo 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, search, status, checked_in, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const max = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabaseForUser(ctx).from("registrations").select("id, event_id, lead_name, lead_email, lead_whatsapp, status, checked_in_at, created_at").eq("event_id", event_id).order("created_at", { ascending: false }).limit(max);
    if (status) query = query.eq("status", status);
    if (checked_in === true) query = query.not("checked_in_at", "is", null);
    if (checked_in === false) query = query.is("checked_in_at", null);
    if (search) {
      const term = search.replace(/[%,]/g, " ").trim();
      query = query.or(
        `lead_name.ilike.%${term}%,lead_email.ilike.%${term}%,lead_whatsapp.ilike.%${term}%`
      );
    }
    const { data, error } = await query;
    if (error) return failure(error.message);
    return ok({ count: data?.length ?? 0, registrations: data ?? [] });
  }
});

// src/lib/mcp/tools/check-in-registration.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var check_in_registration_default = defineTool4({
  name: "check_in_registration",
  title: "Fazer check-in de inscrito",
  description: "Registra o check-in (presen\xE7a) de um inscrito pelo ID da inscri\xE7\xE3o. Se j\xE1 houver check-in, informa o hor\xE1rio existente.",
  inputSchema: {
    registration_id: z4.string().describe("ID (uuid) da inscri\xE7\xE3o.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ registration_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: existing, error: readError } = await supabase.from("registrations").select("id, lead_name, lead_email, checked_in_at, event_id").eq("id", registration_id).maybeSingle();
    if (readError) return failure(readError.message);
    if (!existing) return failure("Inscri\xE7\xE3o n\xE3o encontrada ou sem permiss\xE3o de acesso.");
    if (existing.checked_in_at) {
      return ok({ already_checked_in: true, registration: existing });
    }
    const { data, error } = await supabase.from("registrations").update({ checked_in_at: (/* @__PURE__ */ new Date()).toISOString(), status: "attended" }).eq("id", registration_id).select("id, lead_name, lead_email, status, checked_in_at, event_id").maybeSingle();
    if (error) return failure(error.message);
    return ok({ already_checked_in: false, registration: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "ahwecyjzzczcwunptxae";
var mcp_default = defineMcp({
  name: "centerfrios-eventos-mcp",
  title: "Centerfrios Eventos",
  version: "0.1.0",
  instructions: "Ferramentas para a plataforma de eventos Centerfrios. Use `list_events` para encontrar eventos, `get_event_stats` para o resumo de inscri\xE7\xF5es e presen\xE7as, `list_registrations` para consultar inscritos (busca por nome, e-mail ou WhatsApp) e `check_in_registration` para registrar a presen\xE7a de um inscrito. Todas as a\xE7\xF5es s\xE3o executadas como o usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_events_default, get_event_stats_default, list_registrations_default, check_in_registration_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
